### ISSUE TITLE
烧写器可以推荐下吗 小白想复刻

### ISSUE THREAD

**Issue by 1zyao** [susabolca/cc2640r2-etag#10]
烧写器可以推荐下吗 小白想复刻 直接搜给的那个几个都要几百以上 超预算了qwq

**Comment by susabolca** [comment]
我还有多1个，你要闲鱼上找我下？xds110仿真器

**Comment by susabolca** [comment]
咸鱼看看？

**Comment by 1zyao** [comment]
闲鱼有xds110卖80的  但是不保好坏

**Comment by jam422470459** [comment]
下载编译好hex, 用jlink(4线jtag)直接烧录. 感觉弄个xds110(cjtag,2线)不划算. 图片中的飞线(D5,D6)就是jlink烧录线其中的两根.

**Comment by tsl0922** [comment]
> 下载编译好hex, 用jlink(4线jtag)直接烧录. 感觉弄个xds110(cjtag,2线)不划算. 图片中的飞线(D5,D6)就是jlink烧录线其中的两根.

我做了个 [J-Link-OB-RA4M2](https://oshwhub.com/tsl0922/j-link-ob-ra4m2)，支持 cJTAG，可以直接刷这个，成本 20-30 块，闲鱼也有卖的 60 块。

**Comment by jam422470459** [comment]
> > 下载编译好hex, 用jlink(4线jtag)直接烧录. 感觉弄个xds110(cjtag,2线)不划算. 图片中的飞线(D5,D6)就是jlink烧录线其中的两根.
> 
> 我做了个 [J-Link-OB-RA4M2](https://oshwhub.com/tsl0922/j-link-ob-ra4m2)，支持 cJTAG，可以直接刷这个，成本 20-30 块，闲鱼也有卖的 60 块。

咱们有缘啦，我一直能碰到你，无论在哪都能找到你，我是墨墨。
