### ISSUE TITLE
请问2.66寸待机电流300多微安，是正常的吗？

### ISSUE THREAD

**Issue by reiyawea** [susabolca/cc2640r2-etag#17]
之前在launchpad上实现过10微安左右的待机电流，感觉300多微安有点高了，怀疑是哪里没做对，想找您确认一下待机电流。

**Comment by reiyawea** [comment]
经过一通折腾，电流已经降到70多微安了，离10微安还有一段路要走啊。。

**Comment by zhaolei0505** [comment]
700ua 应该不正常的，是 v0.0.7 的 2in66 版本么？

**Comment by reiyawea** [comment]
是最新0.0.7版本的。刚刷完固件会刷屏8:00，之后电流大约300uA。大约1分钟后，电流会升到2mA，也不刷屏。
请问您测过待机电流吗？是多少呢？

**Comment by reiyawea** [comment]
是0.0.7版本的。
请问能发一下这个价签的PCB照片吗？我想研究一下是不是哪里漏电了。

**Comment by susabolca** [comment]
可能和 ram overflow 有关，切换到图片模式之后，可能会导致蓝牙状态错误导致耗电异常。
这个问题修复在 #18 
可否尝试下 v0.0.8 是否修复，感谢支持。

我的实际测试，
待机电流在 5ua，BLE 发送 adv 时会升高到 200ua 左右。如果连接上蓝牙，会持续 200-300ua 左右电流。断开之后，能重回 5ua 待机电流。(万用表精度有限，可能会有些误差)

**Comment by reiyawea** [comment]
v0.0.8平均电流均220uA，每隔1分钟电流会升到1.5mA持续15秒，但时钟显示不刷新。

**Comment by reiyawea** [comment]
PS我也做了个蓝牙传图程序，待机电流是70uA。同一个程序框架在2.9寸价签上可以低至10uA以下。能否麻烦您烧录并测一下电流？我想先排除硬件问题。上电后红蓝灯交替闪烁后即进入待机。
[simple_peripheral_cc2640r2lp_app.zip](https://github.com/user-attachments/files/16267440/simple_peripheral_cc2640r2lp_app.zip)
先行谢过

**Comment by susabolca** [comment]
你的程序刷到 2in66 之后，交替闪烁之后待机电流 45ua。

**Comment by reiyawea** [comment]
感谢！
换了片屏还是70uA，看来不是屏漏电，是2640里面有问题，这下成谜了。之后您有固件更新我会持续跟进的。

**Comment by susabolca** [comment]
> v0.0.8平均电流均220uA，每隔1分钟电流会升到1.5mA持续15秒，但时钟显示不刷新。

有可能是屏不同导致，LUT 不适配所以不刷新。

我只有一个 2in66，pcb 如下图所示，
![pcb_2in66](https://github.com/user-attachments/assets/c2c54fd8-81c5-45e8-ac78-c302ad50cfa5)
屏线上有编号 FPC-A003 HB (但我不感觉是型号)

**Comment by reiyawea** [comment]
排线和你的一样。或许我这个是SSD1680，你的是1680A，LUT结构不一样。开局全刷用OTP LUT所以能刷出来。

**Comment by susabolca** [comment]
> 排线和你的一样。或许我这个是SSD1680，你的是1680A，LUT结构不一样。开局全刷用OTP LUT所以能刷出来。

可以用 2.9 BWR 的固件试试

**Comment by reiyawea** [comment]
试过了0.0.7版2.9 BWR固件，待机电流能降到10uA左右。看来是我的程序没写好。

**Comment by reiyawea** [comment]
找到问题了。我把驱动红蓝LED的IO设成了开漏模式，但没有关闭输入缓冲器，引脚浮空电平不定导致了额外功耗。
将IO设为推挽，或关闭输入缓冲器，即可解决了。
我把广播间隔设为6秒，测定待机电流可低至2uA。
另外，建议关闭BUSY脚的上下拉电阻，避免BUSY电平为low时产生额外功耗。
