### ISSUE TITLE
烧录夹子在哪里买的，求推荐

### ISSUE THREAD

**Issue by HapCoderWei** [susabolca/cc2640r2-etag#8]
看到你的烧录夹具很好用，想问下在哪买的，我找到的夹具都不支持价签的尺寸，需要单独定做，或者只能把价签的板子拆除了再用

**Comment by susabolca** [comment]
![tb_image_share_1715408250503 jpg](https://github.com/susabolca/cc2640r2-etag/assets/9492224/f900476a-4c9d-4ebf-b8d9-0b20c833a7ff)
我用的这个，淘宝的。夹子不够长，我是用厚一点的亚克力板加长了。2in13和2in9都可以夹的上。

**Comment by HapCoderWei** [comment]
好的，我也是用的这样的夹子，我明白了，谢谢。也感谢你的项目，很有帮助👍
